import type { EngineConfig } from "@/lib/analysis";
import type { PlayingStyle } from "@/types/chess";

export type PersonalityKind = "legend" | "fiction" | "science" | "archetype";

export type LocalizedText = { fr: string; en: string };

/** 0–100 style axes shown on the radar + risk (slider / humanizer). */
export type PersonalityStyleDimensions = PlayingStyle & {
  /** Chance of speculative / imprecise moves (maps to humanBlunderInterval). */
  risk: number;
};

export type PersonalityOpeningRef = { id: string; weight: number };

export type PersonalityAccent =
  | "amber"
  | "rose"
  | "cyan"
  | "violet"
  | "emerald"
  | "orange"
  | "sky"
  | "fuchsia"
  | "lime"
  | "stone"
  | "red"
  | "indigo"
  | "yellow"
  | "teal"
  | "slate";

/**
 * Fritz-style personality opponent: a seeded persona (openings + style dims)
 * that compiles to the existing EngineConfig / Stockfish humanizer path.
 */
export interface PersonalityOpponent {
  id: string;
  kind: PersonalityKind;
  name: LocalizedText;
  bio: LocalizedText;
  era: LocalizedText;
  archetype: LocalizedText;
  years?: string;
  portraitInitials: string;
  /** Cartoon caricature under /public/personalities — never a real photo. */
  portraitUrl?: string;
  accent: PersonalityAccent;
  style: PersonalityStyleDimensions;
  playStyle: EngineConfig["playStyle"];
  elo: number;
  difficulty: 1 | 2 | 3 | 4 | 5;
  favoriteOpeningId: string;
  whiteOpenings: PersonalityOpeningRef[];
  blackOpenings: PersonalityOpeningRef[];
  depth: number;
  timeControl: number;
  threads: number;
}

export const PERSONALITY_OPPONENTS: PersonalityOpponent[] = [
  {
    id: "morphy",
    kind: "legend",
    name: { fr: "Paul Morphy", en: "Paul Morphy" },
    bio: {
      fr: "Génie romantique de la Nouvelle-Orléans : développement rapide, ouvertures ouvertes et attaques sur le roi.",
      en: "Romantic genius from New Orleans: rapid development, open games, and king hunts.",
    },
    era: { fr: "Ère romantique", en: "Romantic era" },
    archetype: { fr: "Romantique", en: "Romantic" },
    years: "1837–1884",
    portraitInitials: "PM",
    portraitUrl: "/personalities/morphy.webp",
    accent: "amber",
    style: {
      aggression: 88,
      tactical: 90,
      positional: 28,
      endgame: 42,
      openingTheory: 45,
      timeManagement: 55,
      risk: 82,
    },
    playStyle: "agressif",
    elo: 2700,
    difficulty: 5,
    favoriteOpeningId: "evans-gambit",
    whiteOpenings: [
      { id: "evans-gambit", weight: 45 },
      { id: "italian-game", weight: 35 },
      { id: "kings-gambit", weight: 20 },
    ],
    blackOpenings: [
      { id: "italian-game", weight: 55 },
      { id: "evans-gambit", weight: 45 },
    ],
    depth: 16,
    timeControl: 900,
    threads: 2,
  },
  {
    id: "lasker",
    kind: "legend",
    name: { fr: "Emanuel Lasker", en: "Emanuel Lasker" },
    bio: {
      fr: "Champion du monde pragmatique : psychologie, prises d’échange et positions légèrement inférieures mais jouables.",
      en: "Pragmatic world champion: psychology, exchange-minded play, and slightly worse but playable positions.",
    },
    era: { fr: "École classique", en: "Classical school" },
    archetype: { fr: "Pragmatique", en: "Pragmatic" },
    years: "1868–1941",
    portraitInitials: "EL",
    portraitUrl: "/personalities/lasker.webp",
    accent: "violet",
    style: {
      aggression: 55,
      tactical: 62,
      positional: 68,
      endgame: 78,
      openingTheory: 58,
      timeManagement: 80,
      risk: 64,
    },
    playStyle: "équilibré",
    elo: 2720,
    difficulty: 5,
    favoriteOpeningId: "spanish-opening",
    whiteOpenings: [
      { id: "spanish-opening", weight: 55 },
      { id: "queens-gambit", weight: 30 },
      { id: "london-system", weight: 15 },
    ],
    blackOpenings: [
      { id: "french-defense", weight: 45 },
      { id: "sicilian-defense", weight: 30 },
      { id: "italian-game", weight: 25 },
    ],
    depth: 16,
    timeControl: 900,
    threads: 2,
  },
  {
    id: "capablanca",
    kind: "legend",
    name: { fr: "José Raúl Capablanca", en: "José Raúl Capablanca" },
    bio: {
      fr: "La machine à simplifier : clarté positionnelle, finales impeccables et peu de risques inutiles.",
      en: "The simplifying machine: positional clarity, impeccable endgames, and few unnecessary risks.",
    },
    era: { fr: "École cubaine", en: "Cuban school" },
    archetype: { fr: "Positionnel", en: "Positional" },
    years: "1888–1942",
    portraitInitials: "JC",
    portraitUrl: "/personalities/capablanca.webp",
    accent: "cyan",
    style: {
      aggression: 32,
      tactical: 40,
      positional: 92,
      endgame: 95,
      openingTheory: 60,
      timeManagement: 88,
      risk: 18,
    },
    playStyle: "positionnel",
    elo: 2780,
    difficulty: 5,
    favoriteOpeningId: "queens-gambit",
    whiteOpenings: [
      { id: "queens-gambit", weight: 50 },
      { id: "spanish-opening", weight: 30 },
      { id: "english-opening", weight: 20 },
    ],
    blackOpenings: [
      { id: "nimzo-indian-defense", weight: 40 },
      { id: "caro-kann", weight: 35 },
      { id: "french-defense", weight: 25 },
    ],
    depth: 16,
    timeControl: 900,
    threads: 4,
  },
  {
    id: "tal",
    kind: "legend",
    name: { fr: "Mikhail Tal", en: "Mikhail Tal" },
    bio: {
      fr: "Le magicien de Riga : sacrifices, initiative permanente et chaos calculé.",
      en: "The magician from Riga: sacrifices, constant initiative, and calculated chaos.",
    },
    era: { fr: "École soviétique", en: "Soviet school" },
    archetype: { fr: "Tactique", en: "Tactical" },
    years: "1936–1992",
    portraitInitials: "MT",
    portraitUrl: "/personalities/tal.webp",
    accent: "rose",
    style: {
      aggression: 96,
      tactical: 98,
      positional: 22,
      endgame: 48,
      openingTheory: 62,
      timeManagement: 50,
      risk: 92,
    },
    playStyle: "tactique",
    elo: 2750,
    difficulty: 5,
    favoriteOpeningId: "sicilian-defense",
    whiteOpenings: [
      { id: "italian-game", weight: 30 },
      { id: "spanish-opening", weight: 25 },
      { id: "scotch-game", weight: 25 },
      { id: "kings-gambit", weight: 20 },
    ],
    blackOpenings: [
      { id: "sicilian-defense", weight: 70 },
      { id: "kings-indian-defense", weight: 30 },
    ],
    depth: 16,
    timeControl: 900,
    threads: 2,
  },
  {
    id: "fischer",
    kind: "legend",
    name: { fr: "Bobby Fischer", en: "Bobby Fischer" },
    bio: {
      fr: "Théorie chirurgicale : Espagnole et Najdorf, pression constante, peu de compromis.",
      en: "Surgical theory: Ruy Lopez and Najdorf, constant pressure, few compromises.",
    },
    era: { fr: "Guerre froide", en: "Cold War" },
    archetype: { fr: "Théoricien", en: "Theoretician" },
    years: "1943–2008",
    portraitInitials: "BF",
    portraitUrl: "/personalities/fischer.webp",
    accent: "orange",
    style: {
      aggression: 78,
      tactical: 80,
      positional: 70,
      endgame: 82,
      openingTheory: 96,
      timeManagement: 85,
      risk: 48,
    },
    playStyle: "agressif",
    elo: 2880,
    difficulty: 5,
    favoriteOpeningId: "spanish-opening",
    whiteOpenings: [
      { id: "spanish-opening", weight: 60 },
      { id: "kings-indian-attack", weight: 25 },
      { id: "italian-game", weight: 15 },
    ],
    blackOpenings: [
      { id: "sicilian-defense", weight: 75 },
      { id: "kings-indian-defense", weight: 25 },
    ],
    depth: 18,
    timeControl: 1000,
    threads: 4,
  },
  {
    id: "karpov",
    kind: "legend",
    name: { fr: "Anatoly Karpov", en: "Anatoly Karpov" },
    bio: {
      fr: "Le boa constrictor : étau positionnel, Caro-Kann, échanges favorables et patience.",
      en: "The boa constrictor: positional squeeze, Caro-Kann, favourable exchanges, and patience.",
    },
    era: { fr: "École soviétique", en: "Soviet school" },
    archetype: { fr: "Solide", en: "Solid" },
    years: "1951–",
    portraitInitials: "AK",
    portraitUrl: "/personalities/karpov.webp",
    accent: "emerald",
    style: {
      aggression: 28,
      tactical: 45,
      positional: 94,
      endgame: 90,
      openingTheory: 82,
      timeManagement: 92,
      risk: 16,
    },
    playStyle: "solide",
    elo: 2780,
    difficulty: 5,
    favoriteOpeningId: "spanish-opening",
    whiteOpenings: [
      { id: "spanish-opening", weight: 45 },
      { id: "queens-gambit", weight: 35 },
      { id: "english-opening", weight: 20 },
    ],
    blackOpenings: [
      { id: "caro-kann", weight: 50 },
      { id: "nimzo-indian-defense", weight: 35 },
      { id: "french-defense", weight: 15 },
    ],
    depth: 17,
    timeControl: 950,
    threads: 4,
  },
  {
    id: "philidor",
    kind: "legend",
    name: { fr: "François-André Philidor", en: "François-André Philidor" },
    bio: {
      fr: "Les pions sont l’âme des échecs : structures lentes, finales longues et patience des Lumières.",
      en: "Pawns are the soul of chess: slow structures, long endgames, and Enlightenment patience.",
    },
    era: { fr: "Siècle des Lumières", en: "Enlightenment" },
    archetype: { fr: "Finaliste", en: "Endgame" },
    years: "1726–1795",
    portraitInitials: "FP",
    portraitUrl: "/personalities/philidor.webp",
    accent: "stone",
    style: {
      aggression: 30,
      tactical: 36,
      positional: 82,
      endgame: 98,
      openingTheory: 22,
      timeManagement: 74,
      risk: 20,
    },
    playStyle: "positionnel",
    elo: 2620,
    difficulty: 5,
    favoriteOpeningId: "italian-game",
    whiteOpenings: [
      { id: "italian-game", weight: 55 },
      { id: "vienna-game", weight: 30 },
      { id: "scotch-game", weight: 15 },
    ],
    blackOpenings: [
      { id: "italian-game", weight: 50 },
      { id: "french-defense", weight: 35 },
      { id: "caro-kann", weight: 15 },
    ],
    depth: 15,
    timeControl: 850,
    threads: 2,
  },
  {
    id: "steinitz",
    kind: "legend",
    name: { fr: "Wilhelm Steinitz", en: "Wilhelm Steinitz" },
    bio: {
      fr: "Fondateur de l’école scientifique : petits avantages, roi au centre, défense avant l’attaque.",
      en: "Founder of the scientific school: small advantages, a central king, defense before attack.",
    },
    era: { fr: "École scientifique", en: "Scientific school" },
    archetype: { fr: "Scientifique", en: "Scientific" },
    years: "1836–1900",
    portraitInitials: "WS",
    portraitUrl: "/personalities/steinitz.webp",
    accent: "red",
    style: {
      aggression: 24,
      tactical: 42,
      positional: 90,
      endgame: 86,
      openingTheory: 46,
      timeManagement: 91,
      risk: 14,
    },
    playStyle: "solide",
    elo: 2700,
    difficulty: 5,
    favoriteOpeningId: "spanish-opening",
    whiteOpenings: [
      { id: "spanish-opening", weight: 45 },
      { id: "queens-gambit", weight: 35 },
      { id: "vienna-game", weight: 20 },
    ],
    blackOpenings: [
      { id: "french-defense", weight: 55 },
      { id: "caro-kann", weight: 30 },
      { id: "italian-game", weight: 15 },
    ],
    depth: 16,
    timeControl: 900,
    threads: 2,
  },
  {
    id: "nimzowitsch",
    kind: "legend",
    name: { fr: "Aron Nimzowitsch", en: "Aron Nimzowitsch" },
    bio: {
      fr: "Le prophète hypermoderne : blocage, surprotection et centre contrôlé à distance.",
      en: "The hypermodern prophet: blockade, overprotection, and a centre controlled from afar.",
    },
    era: { fr: "Hypermodernisme", en: "Hypermodernism" },
    archetype: { fr: "Prophylactique", en: "Prophylactic" },
    years: "1886–1935",
    portraitInitials: "AN",
    portraitUrl: "/personalities/nimzowitsch.webp",
    accent: "indigo",
    style: {
      aggression: 42,
      tactical: 50,
      positional: 86,
      endgame: 68,
      openingTheory: 76,
      timeManagement: 66,
      risk: 40,
    },
    playStyle: "positionnel",
    elo: 2680,
    difficulty: 5,
    favoriteOpeningId: "reti-opening",
    whiteOpenings: [
      { id: "reti-opening", weight: 45 },
      { id: "english-opening", weight: 35 },
      { id: "catalan-opening", weight: 20 },
    ],
    blackOpenings: [
      { id: "nimzo-indian-defense", weight: 50 },
      { id: "french-defense", weight: 30 },
      { id: "caro-kann", weight: 20 },
    ],
    depth: 16,
    timeControl: 900,
    threads: 2,
  },
  {
    id: "alekhine",
    kind: "legend",
    name: { fr: "Alexandre Alekhine", en: "Alexander Alekhine" },
    bio: {
      fr: "Champion dynamique : complications concrètes, défense Alekhine et attaques sur les deux ailes.",
      en: "Dynamic champion: concrete complications, Alekhine’s Defence, and attacks on both wings.",
    },
    era: { fr: "Entre-deux-guerres", en: "Interwar years" },
    archetype: { fr: "Dynamique", en: "Dynamic" },
    years: "1892–1946",
    portraitInitials: "AA",
    portraitUrl: "/personalities/alekhine.webp",
    accent: "yellow",
    style: {
      aggression: 84,
      tactical: 86,
      positional: 46,
      endgame: 76,
      openingTheory: 78,
      timeManagement: 58,
      risk: 70,
    },
    playStyle: "agressif",
    elo: 2790,
    difficulty: 5,
    favoriteOpeningId: "alekhine-defense",
    whiteOpenings: [
      { id: "queens-gambit", weight: 40 },
      { id: "vienna-game", weight: 35 },
      { id: "spanish-opening", weight: 25 },
    ],
    blackOpenings: [
      { id: "alekhine-defense", weight: 45 },
      { id: "french-defense", weight: 30 },
      { id: "sicilian-defense", weight: 25 },
    ],
    depth: 17,
    timeControl: 950,
    threads: 4,
  },
  {
    id: "larsen",
    kind: "legend",
    name: { fr: "Bent Larsen", en: "Bent Larsen" },
    bio: {
      fr: "Le rebelle des flancs : Bird, Anglaise et idées hors théorie pour déséquilibrer dès le coup 1.",
      en: "The flank rebel: Bird, English, and offbeat ideas that unbalance the game from move one.",
    },
    era: { fr: "Années 1970", en: "1970s" },
    archetype: { fr: "Atypique", en: "Unorthodox" },
    years: "1935–2010",
    portraitInitials: "BL",
    portraitUrl: "/personalities/larsen.webp",
    accent: "teal",
    style: {
      aggression: 74,
      tactical: 72,
      positional: 40,
      endgame: 55,
      openingTheory: 32,
      timeManagement: 46,
      risk: 80,
    },
    playStyle: "agressif",
    elo: 2660,
    difficulty: 5,
    favoriteOpeningId: "bird-opening",
    whiteOpenings: [
      { id: "bird-opening", weight: 50 },
      { id: "english-opening", weight: 30 },
      { id: "reti-opening", weight: 20 },
    ],
    blackOpenings: [
      { id: "sicilian-defense", weight: 40 },
      { id: "alekhine-defense", weight: 35 },
      { id: "grunfeld-defense", weight: 25 },
    ],
    depth: 16,
    timeControl: 900,
    threads: 2,
  },
  {
    id: "kasparov",
    kind: "legend",
    name: { fr: "Garry Kasparov", en: "Garry Kasparov" },
    bio: {
      fr: "Préparation explosive : Écossaise, Sicilienne et Indienne du Roi, initiative dès l’ouverture.",
      en: "Explosive preparation: Scotch, Sicilian, and King’s Indian, with initiative from the opening.",
    },
    era: { fr: "Fin du XXe siècle", en: "Late 20th century" },
    archetype: { fr: "Initiateur", en: "Initiator" },
    years: "1963–",
    portraitInitials: "GK",
    portraitUrl: "/personalities/kasparov.webp",
    accent: "fuchsia",
    style: {
      aggression: 90,
      tactical: 88,
      positional: 55,
      endgame: 84,
      openingTheory: 95,
      timeManagement: 72,
      risk: 58,
    },
    playStyle: "agressif",
    elo: 2851,
    difficulty: 5,
    favoriteOpeningId: "scotch-game",
    whiteOpenings: [
      { id: "scotch-game", weight: 40 },
      { id: "queens-gambit", weight: 35 },
      { id: "english-opening", weight: 25 },
    ],
    blackOpenings: [
      { id: "sicilian-defense", weight: 45 },
      { id: "kings-indian-defense", weight: 30 },
      { id: "grunfeld-defense", weight: 25 },
    ],
    depth: 18,
    timeControl: 1000,
    threads: 4,
  },
  {
    id: "carlsen",
    kind: "legend",
    name: { fr: "Magnus Carlsen", en: "Magnus Carlsen" },
    bio: {
      fr: "Universel de l’ère des moteurs : Anglaise, Catalane, et une finale gagnée à la patience.",
      en: "Universal player of the engine era: English, Catalan, and endgames ground out by patience.",
    },
    era: { fr: "Ère des moteurs", en: "Engine era" },
    archetype: { fr: "Universel", en: "Universal" },
    years: "1990–",
    portraitInitials: "MC",
    portraitUrl: "/personalities/carlsen.webp",
    accent: "slate",
    style: {
      aggression: 48,
      tactical: 58,
      positional: 74,
      endgame: 98,
      openingTheory: 68,
      timeManagement: 96,
      risk: 28,
    },
    playStyle: "équilibré",
    elo: 2882,
    difficulty: 5,
    favoriteOpeningId: "english-opening",
    whiteOpenings: [
      { id: "english-opening", weight: 40 },
      { id: "catalan-opening", weight: 30 },
      { id: "queens-gambit", weight: 20 },
      { id: "london-system", weight: 10 },
    ],
    blackOpenings: [
      { id: "caro-kann", weight: 30 },
      { id: "sicilian-defense", weight: 25 },
      { id: "nimzo-indian-defense", weight: 25 },
      { id: "grunfeld-defense", weight: 20 },
    ],
    depth: 18,
    timeControl: 1000,
    threads: 4,
  },
  {
    id: "hal",
    kind: "fiction",
    name: { fr: "HAL", en: "HAL" },
    bio: {
      fr: "Calculateur impassible : aucun risque inutile, des finales exactes et un contrôle froid du centre.",
      en: "Impassive calculator: no unnecessary risk, exact endgames, and cold control of the centre.",
    },
    era: { fr: "Intelligence artificielle", en: "Artificial intelligence" },
    archetype: { fr: "Machine", en: "Machine" },
    years: "2001",
    portraitInitials: "HAL",
    portraitUrl: "/personalities/hal.webp",
    accent: "red",
    style: {
      aggression: 12,
      tactical: 28,
      positional: 92,
      endgame: 96,
      openingTheory: 99,
      timeManagement: 99,
      risk: 2,
    },
    playStyle: "positionnel",
    elo: 3100,
    difficulty: 5,
    favoriteOpeningId: "english-opening",
    whiteOpenings: [
      { id: "english-opening", weight: 50 },
      { id: "catalan-opening", weight: 30 },
      { id: "queens-gambit", weight: 20 },
    ],
    blackOpenings: [
      { id: "caro-kann", weight: 50 },
      { id: "french-defense", weight: 35 },
      { id: "nimzo-indian-defense", weight: 15 },
    ],
    depth: 20,
    timeControl: 1200,
    threads: 4,
  },
  {
    id: "holmes",
    kind: "fiction",
    name: { fr: "Sherlock Holmes", en: "Sherlock Holmes" },
    bio: {
      fr: "Déduction à Baker Street : observer, écarter l’impossible, puis resserrer la position.",
      en: "Baker Street deduction: observe, rule out the impossible, then tighten the position.",
    },
    era: { fr: "Baker Street", en: "Baker Street" },
    archetype: { fr: "Déductif", en: "Deductive" },
    years: "1887",
    portraitInitials: "SH",
    portraitUrl: "/personalities/holmes.webp",
    accent: "sky",
    style: {
      aggression: 34,
      tactical: 58,
      positional: 84,
      endgame: 82,
      openingTheory: 66,
      timeManagement: 92,
      risk: 18,
    },
    playStyle: "positionnel",
    elo: 2720,
    difficulty: 5,
    favoriteOpeningId: "spanish-opening",
    whiteOpenings: [
      { id: "spanish-opening", weight: 50 },
      { id: "queens-gambit", weight: 30 },
      { id: "italian-game", weight: 20 },
    ],
    blackOpenings: [
      { id: "french-defense", weight: 45 },
      { id: "caro-kann", weight: 35 },
      { id: "nimzo-indian-defense", weight: 20 },
    ],
    depth: 17,
    timeControl: 950,
    threads: 2,
  },
  {
    id: "red-queen",
    kind: "fiction",
    name: { fr: "La Reine Rouge", en: "The Red Queen" },
    bio: {
      fr: "Reine du miroir : elle impose le tempo, sacrifie et ne laisse personne souffler.",
      en: "Queen of the looking-glass: she dictates the tempo, sacrifices, and never lets you breathe.",
    },
    era: { fr: "De l’autre côté du miroir", en: "Through the looking-glass" },
    archetype: { fr: "Impérieuse", en: "Imperious" },
    years: "1871",
    portraitInitials: "RQ",
    portraitUrl: "/personalities/red-queen.webp",
    accent: "rose",
    style: {
      aggression: 96,
      tactical: 90,
      positional: 18,
      endgame: 28,
      openingTheory: 32,
      timeManagement: 38,
      risk: 90,
    },
    playStyle: "tactique",
    elo: 2680,
    difficulty: 5,
    favoriteOpeningId: "kings-gambit",
    whiteOpenings: [
      { id: "kings-gambit", weight: 50 },
      { id: "evans-gambit", weight: 30 },
      { id: "scotch-game", weight: 20 },
    ],
    blackOpenings: [
      { id: "sicilian-defense", weight: 45 },
      { id: "budapest-gambit", weight: 35 },
      { id: "kings-indian-defense", weight: 20 },
    ],
    depth: 16,
    timeControl: 800,
    threads: 2,
  },
  {
    id: "moriarty",
    kind: "fiction",
    name: { fr: "Professeur Moriarty", en: "Professor Moriarty" },
    bio: {
      fr: "Le consultant criminel : préparation froide, complications calculées et pièges dès l’ouverture.",
      en: "The consulting criminal: cold preparation, calculated complications, and traps from the opening.",
    },
    era: { fr: "Londres criminel", en: "Criminal London" },
    archetype: { fr: "Machiavélique", en: "Machiavellian" },
    years: "1893",
    portraitInitials: "PM",
    portraitUrl: "/personalities/moriarty.webp",
    accent: "violet",
    style: {
      aggression: 74,
      tactical: 82,
      positional: 50,
      endgame: 72,
      openingTheory: 88,
      timeManagement: 76,
      risk: 48,
    },
    playStyle: "agressif",
    elo: 2780,
    difficulty: 5,
    favoriteOpeningId: "queens-gambit",
    whiteOpenings: [
      { id: "queens-gambit", weight: 45 },
      { id: "vienna-game", weight: 30 },
      { id: "english-opening", weight: 25 },
    ],
    blackOpenings: [
      { id: "sicilian-defense", weight: 50 },
      { id: "alekhine-defense", weight: 30 },
      { id: "french-defense", weight: 20 },
    ],
    depth: 18,
    timeControl: 1000,
    threads: 4,
  },
  {
    id: "newton",
    kind: "science",
    name: { fr: "Isaac Newton", en: "Isaac Newton" },
    bio: {
      fr: "Les lois du jeu : développement classique, petits avantages accumulés et finales calculées.",
      en: "The laws of the game: classical development, accumulated small advantages, and calculated endgames.",
    },
    era: { fr: "Révolution scientifique", en: "Scientific revolution" },
    archetype: { fr: "Mécaniste", en: "Mechanistic" },
    years: "1643–1727",
    portraitInitials: "IN",
    portraitUrl: "/personalities/newton.webp",
    accent: "stone",
    style: {
      aggression: 26,
      tactical: 38,
      positional: 91,
      endgame: 90,
      openingTheory: 34,
      timeManagement: 94,
      risk: 10,
    },
    playStyle: "positionnel",
    elo: 2690,
    difficulty: 5,
    favoriteOpeningId: "italian-game",
    whiteOpenings: [
      { id: "italian-game", weight: 50 },
      { id: "spanish-opening", weight: 30 },
      { id: "queens-gambit", weight: 20 },
    ],
    blackOpenings: [
      { id: "french-defense", weight: 40 },
      { id: "italian-game", weight: 35 },
      { id: "caro-kann", weight: 25 },
    ],
    depth: 16,
    timeControl: 900,
    threads: 2,
  },
  {
    id: "curie",
    kind: "science",
    name: { fr: "Marie Curie", en: "Marie Curie" },
    bio: {
      fr: "Patience de laboratoire : structures saines, échanges précis et aucune précipitation.",
      en: "Laboratory patience: sound structures, precise exchanges, and no rush.",
    },
    era: { fr: "Laboratoire", en: "Laboratory" },
    archetype: { fr: "Méthodique", en: "Methodical" },
    years: "1867–1934",
    portraitInitials: "MC",
    portraitUrl: "/personalities/curie.webp",
    accent: "emerald",
    style: {
      aggression: 18,
      tactical: 36,
      positional: 90,
      endgame: 78,
      openingTheory: 70,
      timeManagement: 96,
      risk: 8,
    },
    playStyle: "solide",
    elo: 2660,
    difficulty: 5,
    favoriteOpeningId: "catalan-opening",
    whiteOpenings: [
      { id: "catalan-opening", weight: 45 },
      { id: "queens-gambit", weight: 35 },
      { id: "london-system", weight: 20 },
    ],
    blackOpenings: [
      { id: "french-defense", weight: 40 },
      { id: "caro-kann", weight: 40 },
      { id: "nimzo-indian-defense", weight: 20 },
    ],
    depth: 16,
    timeControl: 950,
    threads: 2,
  },
  {
    id: "einstein",
    kind: "science",
    name: { fr: "Albert Einstein", en: "Albert Einstein" },
    bio: {
      fr: "La pensée courbe l’échiquier : Réti, Grünfeld, et des idées qui contrôlent le centre à distance.",
      en: "Thought bends the board: Réti, Grünfeld, and ideas that control the centre from afar.",
    },
    era: { fr: "Relativité", en: "Relativity" },
    archetype: { fr: "Intuitif", en: "Intuitive" },
    years: "1879–1955",
    portraitInitials: "AE",
    portraitUrl: "/personalities/einstein.webp",
    accent: "yellow",
    style: {
      aggression: 52,
      tactical: 60,
      positional: 64,
      endgame: 76,
      openingTheory: 55,
      timeManagement: 68,
      risk: 42,
    },
    playStyle: "équilibré",
    elo: 2700,
    difficulty: 5,
    favoriteOpeningId: "reti-opening",
    whiteOpenings: [
      { id: "reti-opening", weight: 45 },
      { id: "english-opening", weight: 30 },
      { id: "catalan-opening", weight: 25 },
    ],
    blackOpenings: [
      { id: "grunfeld-defense", weight: 40 },
      { id: "alekhine-defense", weight: 35 },
      { id: "nimzo-indian-defense", weight: 25 },
    ],
    depth: 17,
    timeControl: 900,
    threads: 2,
  },
  {
    id: "turing",
    kind: "science",
    name: { fr: "Alan Turing", en: "Alan Turing" },
    bio: {
      fr: "L’algorithme incarné : Gambit dame, Caro-Kann, et une logique qui ne laisse rien au hasard.",
      en: "The algorithm in person: Queen’s Gambit, Caro-Kann, and logic that leaves nothing to chance.",
    },
    era: { fr: "Informatique", en: "Computing" },
    archetype: { fr: "Algorithmique", en: "Algorithmic" },
    years: "1912–1954",
    portraitInitials: "AT",
    portraitUrl: "/personalities/turing.webp",
    accent: "teal",
    style: {
      aggression: 22,
      tactical: 48,
      positional: 80,
      endgame: 86,
      openingTheory: 97,
      timeManagement: 90,
      risk: 6,
    },
    playStyle: "positionnel",
    elo: 2740,
    difficulty: 5,
    favoriteOpeningId: "queens-gambit",
    whiteOpenings: [
      { id: "queens-gambit", weight: 50 },
      { id: "london-system", weight: 30 },
      { id: "english-opening", weight: 20 },
    ],
    blackOpenings: [
      { id: "caro-kann", weight: 55 },
      { id: "french-defense", weight: 25 },
      { id: "nimzo-indian-defense", weight: 20 },
    ],
    depth: 18,
    timeControl: 1000,
    threads: 4,
  },
  {
    id: "hypermodern",
    kind: "archetype",
    name: { fr: "Hypermoderne", en: "Hypermodern" },
    bio: {
      fr: "Contrôle le centre à distance : Réti, Anglaise, Alekhine et Grünfeld.",
      en: "Control the centre from afar: Réti, English, Alekhine, and Grünfeld.",
    },
    era: { fr: "Années 1920", en: "1920s" },
    archetype: { fr: "Hypermoderne", en: "Hypermodern" },
    portraitInitials: "HY",
    accent: "sky",
    style: {
      aggression: 48,
      tactical: 55,
      positional: 78,
      endgame: 62,
      openingTheory: 74,
      timeManagement: 66,
      risk: 52,
    },
    playStyle: "positionnel",
    elo: 2100,
    difficulty: 3,
    favoriteOpeningId: "reti-opening",
    whiteOpenings: [
      { id: "reti-opening", weight: 40 },
      { id: "english-opening", weight: 35 },
      { id: "catalan-opening", weight: 25 },
    ],
    blackOpenings: [
      { id: "alekhine-defense", weight: 35 },
      { id: "grunfeld-defense", weight: 35 },
      { id: "pirc-defense", weight: 30 },
    ],
    depth: 12,
    timeControl: 600,
    threads: 2,
  },
  {
    id: "romantic",
    kind: "archetype",
    name: { fr: "Romantique", en: "Romantic" },
    bio: {
      fr: "Gambits et initiative : Gambit du Roi, Evans, attaques ouvertes à tout prix.",
      en: "Gambits and initiative: King's Gambit, Evans, open attacks at all costs.",
    },
    era: { fr: "XIXe siècle", en: "19th century" },
    archetype: { fr: "Romantique", en: "Romantic" },
    portraitInitials: "RO",
    accent: "fuchsia",
    style: {
      aggression: 92,
      tactical: 88,
      positional: 24,
      endgame: 35,
      openingTheory: 38,
      timeManagement: 42,
      risk: 88,
    },
    playStyle: "agressif",
    elo: 1950,
    difficulty: 3,
    favoriteOpeningId: "kings-gambit",
    whiteOpenings: [
      { id: "kings-gambit", weight: 40 },
      { id: "evans-gambit", weight: 35 },
      { id: "italian-game", weight: 25 },
    ],
    blackOpenings: [
      { id: "sicilian-defense", weight: 40 },
      { id: "budapest-gambit", weight: 35 },
      { id: "alekhine-defense", weight: 25 },
    ],
    depth: 11,
    timeControl: 550,
    threads: 2,
  },
  {
    id: "solid-positional",
    kind: "archetype",
    name: { fr: "Solide positionnel", en: "Solid Positional" },
    bio: {
      fr: "Structures saines : Londres, Dame, Caro-Kann — peu de cibles, beaucoup de patience.",
      en: "Sound structures: London, Queen's Gambit, Caro-Kann — few targets, plenty of patience.",
    },
    era: { fr: "Moderne", en: "Modern" },
    archetype: { fr: "Solide", en: "Solid" },
    portraitInitials: "SP",
    accent: "lime",
    style: {
      aggression: 22,
      tactical: 35,
      positional: 88,
      endgame: 80,
      openingTheory: 58,
      timeManagement: 78,
      risk: 14,
    },
    playStyle: "solide",
    elo: 2050,
    difficulty: 3,
    favoriteOpeningId: "london-system",
    whiteOpenings: [
      { id: "london-system", weight: 50 },
      { id: "queens-gambit", weight: 30 },
      { id: "english-opening", weight: 20 },
    ],
    blackOpenings: [
      { id: "caro-kann", weight: 50 },
      { id: "french-defense", weight: 30 },
      { id: "nimzo-indian-defense", weight: 20 },
    ],
    depth: 12,
    timeControl: 650,
    threads: 2,
  },
];

const BY_ID = new Map(PERSONALITY_OPPONENTS.map((p) => [p.id, p]));

export function getPersonalityOpponent(id: string): PersonalityOpponent | undefined {
  return BY_ID.get(id);
}

export function listPersonalityOpponents(kind?: PersonalityKind): PersonalityOpponent[] {
  if (!kind) return PERSONALITY_OPPONENTS;
  return PERSONALITY_OPPONENTS.filter((p) => p.kind === kind);
}

export function personalityDisplayName(
  opponent: PersonalityOpponent,
  lang: string
): string {
  return lang === "fr" ? opponent.name.fr : opponent.name.en;
}

export function personalityBio(opponent: PersonalityOpponent, lang: string): string {
  return lang === "fr" ? opponent.bio.fr : opponent.bio.en;
}

export function personalityEra(opponent: PersonalityOpponent, lang: string): string {
  return lang === "fr" ? opponent.era.fr : opponent.era.en;
}

export function personalityArchetype(
  opponent: PersonalityOpponent,
  lang: string
): string {
  return lang === "fr" ? opponent.archetype.fr : opponent.archetype.en;
}
