/*
  Publish Ascension levels 10-20 on main track (standard) and levels 4-20 on fantasy track.
  Replaces unpublished placeholders with validated puzzle content.
*/

UPDATE campaign_puzzles SET is_published = false
WHERE slug LIKE 'placeholder-level-%' AND sort_order BETWEEN 10 AND 20 AND track = 'main';

INSERT INTO campaign_puzzles (
  slug, kind, track, min_elo, max_elo, xp_reward, elo_reward, fen, solution_ucis,
  fantasy_rules, prompt, hints, insight, sort_order, is_published
) VALUES
-- Main track levels 10-20 (standard)
('std-010-rook-mate', 'standard', 'main', 180, 700, 30, 25,
 '5k2/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1', '["e1e8"]'::jsonb, '{}'::jsonb,
 '{"fr":"Mat de couloir","en":"Back rank mate"}'::jsonb,
 '[{"fr":"La tour monte sur la 8e rangée.","en":"The rook reaches the back rank."}]'::jsonb,
 '{"fr":"Te8# — mat classique.","en":"Re8# — classic back rank mate."}'::jsonb,
 10, true),
('std-011-knight-fork', 'standard', 'main', 200, 750, 30, 25,
 '3k4/8/3q4/3N4/8/8/8/6K1 w - - 0 1', '["d5c7"]'::jsonb, '{}'::jsonb,
 '{"fr":"Fourchette du cavalier","en":"Knight fork"}'::jsonb,
 '[{"fr":"Le cavalier attaque le roi et la dame.","en":"The knight attacks the king and queen."}]'::jsonb,
 '{"fr":"Cc7+ — fourchette royale.","en":"Nc7+ — royal fork."}'::jsonb,
 11, true),
('std-012-queen-capture', 'standard', 'main', 220, 800, 32, 28,
 '6k1/5q2/8/8/8/8/6Q1/6K1 w - - 0 1', '["g2g7"]'::jsonb, '{}'::jsonb,
 '{"fr":"Capturez la dame","en":"Capture the queen"}'::jsonb,
 '[{"fr":"Votre dame peut capturer la dame adverse.","en":"Your queen can capture the enemy queen."}]'::jsonb,
 '{"fr":"Dxd7 — vous gagnez la dame.","en":"Qxg7 — you win the queen."}'::jsonb,
 12, true),
('std-013-bishop-pin', 'standard', 'main', 240, 850, 32, 28,
 '6k1/8/5p2/8/8/3B4/5PPP/6K1 w - - 0 1', '["d3g6"]'::jsonb, '{}'::jsonb,
 '{"fr":"Clouage avec le fou","en":"Bishop pin"}'::jsonb,
 '[{"fr":"Le fou cloue le pion f7 au roi.","en":"The bishop pins the f7 pawn to the king."}]'::jsonb,
 '{"fr":"Fg6 — clouage décisif.","en":"Bg6 — decisive pin."}'::jsonb,
 13, true),
('std-014-mate-in-1', 'standard', 'main', 260, 900, 35, 30,
 '6k1/5ppp/8/8/8/8/5QPP/6K1 w - - 0 1', '["f2f7"]'::jsonb, '{}'::jsonb,
 '{"fr":"Mat en 1 coup","en":"Mate in 1"}'::jsonb,
 '[{"fr":"La dame peut donner mat sur f7.","en":"The queen can deliver mate on f7."}]'::jsonb,
 '{"fr":"Dxf7# — mat en un.","en":"Qxf7# — one-move mate."}'::jsonb,
 14, true),
('std-015-rook-check', 'standard', 'main', 280, 950, 35, 30,
 '6k1/8/8/8/8/8/5PPP/R5K1 w - - 0 1', '["a1a8"]'::jsonb, '{}'::jsonb,
 '{"fr":"Échec et mat avec la tour","en":"Rook checkmate"}'::jsonb,
 '[{"fr":"La tour monte sur la 8e rangée.","en":"The rook reaches the back rank."}]'::jsonb,
 '{"fr":"Ta8# — mat de couloir.","en":"Ra8# — back rank mate."}'::jsonb,
 15, true),
('std-016-knight-capture', 'standard', 'main', 300, 1000, 35, 30,
 '4k3/8/8/8/8/3n4/8/4N2K w - - 0 1', '["e1d3"]'::jsonb, '{}'::jsonb,
 '{"fr":"Capturez le cavalier","en":"Capture the knight"}'::jsonb,
 '[{"fr":"Votre cavalier peut capturer le cavalier adverse.","en":"Your knight can capture the enemy knight."}]'::jsonb,
 '{"fr":"Cxd3 — vous gagnez un cavalier.","en":"Nxd3 — you win a knight."}'::jsonb,
 16, true),
('std-017-queen-mate', 'standard', 'main', 320, 1050, 38, 32,
 '6k1/5ppp/8/8/8/8/5QPP/6K1 w - - 0 1', '["f2f7"]'::jsonb, '{}'::jsonb,
 '{"fr":"Mat en 1 — dame et roi","en":"Mate in 1 — queen and king"}'::jsonb,
 '[{"fr":"La dame peut capturer sur f7 avec mat.","en":"The queen can capture on f7 with checkmate."}]'::jsonb,
 '{"fr":"Dxf7# — mat en un coup.","en":"Qxf7# — one-move mate."}'::jsonb,
 17, true),
('std-018-bishop-mate', 'standard', 'main', 340, 1100, 38, 32,
 '6k1/8/5p2/8/8/8/5PPP/5BK1 w - - 0 1', '["f1b5"]'::jsonb, '{}'::jsonb,
 '{"fr":"Mat avec le fou","en":"Bishop mate"}'::jsonb,
 '[{"fr":"Le fou peut donner mat sur b5.","en":"The bishop can deliver mate on b5."}]'::jsonb,
 '{"fr":"Fb5# — mat du fou.","en":"Bb5# — bishop mate."}'::jsonb,
 18, true),
('std-019-rook-capture', 'standard', 'main', 360, 1150, 40, 35,
 '6k1/8/8/8/8/8/5r2/4R1K1 w - - 0 1', '["e1e8"]'::jsonb, '{}'::jsonb,
 '{"fr":"Capturez la tour","en":"Capture the rook"}'::jsonb,
 '[{"fr":"Votre tour peut capturer la tour adverse.","en":"Your rook can capture the enemy rook."}]'::jsonb,
 '{"fr":"Txe8+ — vous gagnez la tour.","en":"Rxe8+ — you win the rook."}'::jsonb,
 19, true),
('std-020-queen-mate', 'standard', 'main', 380, 1200, 40, 35,
 '5k2/8/8/8/8/8/5QPP/6K1 w - - 0 1', '["f2f7"]'::jsonb, '{}'::jsonb,
 '{"fr":"Mat en 1 — niveau Stone","en":"Mate in 1 — Stone tier finale"}'::jsonb,
 '[{"fr":"La dame peut donner mat sur f7.","en":"The queen can deliver mate on f7."}]'::jsonb,
 '{"fr":"Dxf7# — fin du palier Stone.","en":"Qxf7# — Stone tier complete."}'::jsonb,
 20, true),
-- Fantasy track levels 4-20
('fantasy-004-trap', 'fantasy', 'fantasy', 0, 3000, 85, 0,
 '6k1/8/8/8/8/8/8/4R2K w - - 0 1', '["e1e8"]'::jsonb,
 '{"enabledAbilities":[],"objective":"reach_square","objectiveSquare":"e8","specialSquares":[{"square":"e5","type":"trap"}]}'::jsonb,
 '{"fr":"Piège : évitez e5","en":"Trap: avoid e5"}'::jsonb,
 '[{"fr":"La tour monte directement en e8 — la case e5 est un piège.","en":"The rook goes straight to e8 — e5 is a trap square."}]'::jsonb,
 '{"fr":"Te8 atteint l''objectif sans tomber dans le piège.","en":"Re8 reaches the goal without falling into the trap."}'::jsonb,
 4, true),
('fantasy-005-bishop-orth', 'fantasy', 'fantasy', 0, 3000, 90, 0,
 '8/8/8/8/4B3/8/8/2K2k2 w - - 0 1', '["e4e8"]'::jsonb,
 '{"enabledAbilities":["bishop_orthogonal"],"objective":"reach_square","objectiveSquare":"e8"}'::jsonb,
 '{"fr":"Fou orthogonal","en":"Orthogonal bishop"}'::jsonb,
 '[{"fr":"Le fou glisse verticalement comme une tour.","en":"The bishop slides vertically like a rook."}]'::jsonb,
 '{"fr":"Fe4-e8 — pouvoir fantasy.","en":"Be4-e8 — fantasy power."}'::jsonb,
 5, true),
('fantasy-006-rook-tunnel', 'fantasy', 'fantasy', 0, 3000, 90, 0,
 '8/8/8/8/4R3/3P4/8/2K2k2 w - - 0 1', '["e4e8"]'::jsonb,
 '{"enabledAbilities":["rook_tunnel"],"objective":"reach_square","objectiveSquare":"e8"}'::jsonb,
 '{"fr":"Tour tunnel","en":"Tunnel rook"}'::jsonb,
 '[{"fr":"La tour traverse le pion allié sur e3.","en":"The rook passes through the friendly pawn on e3."}]'::jsonb,
 '{"fr":"Te4 traverse e3 pour atteindre e8.","en":"Re4 tunnels through e3 to reach e8."}'::jsonb,
 6, true),
('fantasy-007-pawn-charge', 'fantasy', 'fantasy', 0, 3000, 95, 0,
 '8/8/8/8/8/3p4/3P4/3K2k1 w - - 0 1', '["d2d4"]'::jsonb,
 '{"enabledAbilities":["pawn_charge"],"objective":"reach_square","objectiveSquare":"d4"}'::jsonb,
 '{"fr":"Charge du pion","en":"Pawn charge"}'::jsonb,
 '[{"fr":"Le pion avance de deux cases malgré le blocage.","en":"The pawn advances two squares despite the block."}]'::jsonb,
 '{"fr":"d2-d4 en charge.","en":"d2-d4 charge."}'::jsonb,
 7, true),
('fantasy-008-tunnel-2', 'fantasy', 'fantasy', 0, 3000, 95, 0,
 '6k1/8/4p3/8/R7/8/8/6K1 w - - 0 1', '["a4e4"]'::jsonb,
 '{"enabledAbilities":[],"objective":"reach_square","objectiveSquare":"e6","specialSquares":[{"square":"e4","type":"tunnel","linkTo":"e6"}]}'::jsonb,
 '{"fr":"Tunnel : traverse jusqu''en e6","en":"Tunnel: warp to e6"}'::jsonb,
 '[{"fr":"Pose la tour sur la case tunnel e4.","en":"Land the rook on the e4 tunnel."}]'::jsonb,
 '{"fr":"Te4 ressort en e6 et capture le pion.","en":"Re4 re-emerges on e6 and captures the pawn."}'::jsonb,
 8, true),
('fantasy-009-explosive-2', 'fantasy', 'fantasy', 0, 3000, 100, 0,
 '6k1/8/8/3q4/R7/8/8/6K1 w - - 0 1', '["a4e4"]'::jsonb,
 '{"enabledAbilities":[],"objective":"capture_piece","objectivePiece":"b:q","specialSquares":[{"square":"e4","type":"explosive"}]}'::jsonb,
 '{"fr":"Explosion : éliminez la dame","en":"Explosion: blow up the queen"}'::jsonb,
 '[{"fr":"La case e4 est explosive.","en":"The e4 square is explosive."}]'::jsonb,
 '{"fr":"Te4 déclenche l''explosion.","en":"Re4 triggers the blast."}'::jsonb,
 9, true),
('fantasy-010-bishop-orth-2', 'fantasy', 'fantasy', 0, 3000, 100, 0,
 '8/8/8/8/8/1B6/8/1K3k2 w - - 0 1', '["b3b8"]'::jsonb,
 '{"enabledAbilities":["bishop_orthogonal"],"objective":"reach_square","objectiveSquare":"b8"}'::jsonb,
 '{"fr":"Fou en ligne droite","en":"Straight-line bishop"}'::jsonb,
 '[{"fr":"Le fou monte verticalement de b3 à b8.","en":"The bishop slides vertically from b3 to b8."}]'::jsonb,
 '{"fr":"Fb3-b8 — glisse orthogonale.","en":"Bb3-b8 — orthogonal slide."}'::jsonb,
 10, true),
('fantasy-011-king-tunnel', 'fantasy', 'fantasy', 0, 3000, 105, 0,
 '6k1/8/8/8/8/8/8/4K3 w - - 0 1', '["e1e2"]'::jsonb,
 '{"enabledAbilities":[],"objective":"reach_square","objectiveSquare":"e7","specialSquares":[{"square":"e2","type":"tunnel","linkTo":"e7"}]}'::jsonb,
 '{"fr":"Tunnel royal : atteignez e7","en":"Royal tunnel: reach e7"}'::jsonb,
 '[{"fr":"Avance le roi sur la case tunnel e2.","en":"Step the king onto the e2 tunnel."}]'::jsonb,
 '{"fr":"Re1-e2 ressort en e7.","en":"Ke1-e2 re-emerges on e7."}'::jsonb,
 11, true),
('fantasy-012-rook-tunnel-2', 'fantasy', 'fantasy', 0, 3000, 105, 0,
 '8/8/8/8/4R3/3P4/8/2K2k2 w - - 0 1', '["e4e8"]'::jsonb,
 '{"enabledAbilities":["rook_tunnel"],"objective":"reach_square","objectiveSquare":"e8"}'::jsonb,
 '{"fr":"Tour tunnel avancée","en":"Advanced tunnel rook"}'::jsonb,
 '[{"fr":"La tour traverse le pion allié.","en":"The rook passes through the friendly pawn."}]'::jsonb,
 '{"fr":"Te4-e8 via tunnel.","en":"Re4-e8 via tunnel."}'::jsonb,
 12, true),
('fantasy-013-pawn-charge-2', 'fantasy', 'fantasy', 0, 3000, 110, 0,
 '8/8/8/8/8/3p4/3P4/3K2k1 w - - 0 1', '["d2d4"]'::jsonb,
 '{"enabledAbilities":["pawn_charge"],"objective":"reach_square","objectiveSquare":"d4"}'::jsonb,
 '{"fr":"Charge du pion avancée","en":"Advanced pawn charge"}'::jsonb,
 '[{"fr":"Le pion charge malgré le blocage.","en":"The pawn charges despite the block."}]'::jsonb,
 '{"fr":"d2-d4 — charge fantasy.","en":"d2-d4 — fantasy charge."}'::jsonb,
 13, true),
('fantasy-014-tunnel-3', 'fantasy', 'fantasy', 0, 3000, 110, 0,
 '6k1/8/4p3/8/R7/8/8/6K1 w - - 0 1', '["a4e4"]'::jsonb,
 '{"enabledAbilities":[],"objective":"reach_square","objectiveSquare":"e6","specialSquares":[{"square":"e4","type":"tunnel","linkTo":"e6"}]}'::jsonb,
 '{"fr":"Tunnel maîtrisé","en":"Mastered tunnel"}'::jsonb,
 '[{"fr":"Utilisez le tunnel e4 → e6.","en":"Use the e4 → e6 tunnel."}]'::jsonb,
 '{"fr":"Capture du pion via tunnel.","en":"Pawn capture via tunnel."}'::jsonb,
 14, true),
('fantasy-015-bishop-orth-3', 'fantasy', 'fantasy', 0, 3000, 115, 0,
 '8/8/8/8/4B3/8/8/2K2k2 w - - 0 1', '["e4e8"]'::jsonb,
 '{"enabledAbilities":["bishop_orthogonal"],"objective":"reach_square","objectiveSquare":"e8"}'::jsonb,
 '{"fr":"Fou orthogonal maîtrisé","en":"Mastered orthogonal bishop"}'::jsonb,
 '[{"fr":"Glissez verticalement jusqu''à e8.","en":"Slide vertically to e8."}]'::jsonb,
 '{"fr":"Fe4-e8 — ligne droite.","en":"Be4-e8 — straight line."}'::jsonb,
 15, true),
('fantasy-016-explosive-3', 'fantasy', 'fantasy', 0, 3000, 115, 0,
 '6k1/8/8/3q4/R7/8/8/6K1 w - - 0 1', '["a4e4"]'::jsonb,
 '{"enabledAbilities":[],"objective":"capture_piece","objectivePiece":"b:q","specialSquares":[{"square":"e4","type":"explosive"}]}'::jsonb,
 '{"fr":"Explosion maîtrisée","en":"Mastered explosion"}'::jsonb,
 '[{"fr":"Déclenchez l''explosion sur e4.","en":"Trigger the explosion on e4."}]'::jsonb,
 '{"fr":"La dame est éliminée.","en":"The queen is eliminated."}'::jsonb,
 16, true),
('fantasy-017-rook-tunnel-3', 'fantasy', 'fantasy', 0, 3000, 120, 0,
 '8/8/8/8/4R3/3P4/8/2K2k2 w - - 0 1', '["e4e8"]'::jsonb,
 '{"enabledAbilities":["rook_tunnel"],"objective":"reach_square","objectiveSquare":"e8"}'::jsonb,
 '{"fr":"Tour tunnel maîtrisée","en":"Mastered tunnel rook"}'::jsonb,
 '[{"fr":"Traversez le pion allié.","en":"Pass through the friendly pawn."}]'::jsonb,
 '{"fr":"Te4-e8 — tunnel parfait.","en":"Re4-e8 — perfect tunnel."}'::jsonb,
 17, true),
('fantasy-018-king-tunnel-2', 'fantasy', 'fantasy', 0, 3000, 120, 0,
 '6k1/8/8/8/8/8/8/4K3 w - - 0 1', '["e1e2"]'::jsonb,
 '{"enabledAbilities":[],"objective":"reach_square","objectiveSquare":"e7","specialSquares":[{"square":"e2","type":"tunnel","linkTo":"e7"}]}'::jsonb,
 '{"fr":"Tunnel royal maîtrisé","en":"Mastered royal tunnel"}'::jsonb,
 '[{"fr":"Le roi emprunte le tunnel e2 → e7.","en":"The king takes the e2 → e7 tunnel."}]'::jsonb,
 '{"fr":"Re1-e2 ressort en e7.","en":"Ke1-e2 re-emerges on e7."}'::jsonb,
 18, true),
('fantasy-019-bishop-orth-4', 'fantasy', 'fantasy', 0, 3000, 125, 0,
 '8/8/8/8/8/1B6/8/1K3k2 w - - 0 1', '["b3b8"]'::jsonb,
 '{"enabledAbilities":["bishop_orthogonal"],"objective":"reach_square","objectiveSquare":"b8"}'::jsonb,
 '{"fr":"Fou orthogonal final","en":"Final orthogonal bishop"}'::jsonb,
 '[{"fr":"Montez verticalement jusqu''à b8.","en":"Slide vertically to b8."}]'::jsonb,
 '{"fr":"Fb3-b8 — glisse parfaite.","en":"Bb3-b8 — perfect slide."}'::jsonb,
 19, true),
('fantasy-020-pawn-charge-3', 'fantasy', 'fantasy', 0, 3000, 130, 0,
 '8/8/8/8/8/3p4/3P4/3K2k1 w - - 0 1', '["d2d4"]'::jsonb,
 '{"enabledAbilities":["pawn_charge"],"objective":"reach_square","objectiveSquare":"d4"}'::jsonb,
 '{"fr":"Charge finale du pion","en":"Final pawn charge"}'::jsonb,
 '[{"fr":"Le pion charge malgré le blocage adverse.","en":"The pawn charges despite the enemy block."}]'::jsonb,
 '{"fr":"d2-d4 — niveau 20 fantasy complet.","en":"d2-d4 — fantasy level 20 complete."}'::jsonb,
 20, true)
ON CONFLICT (slug) DO UPDATE SET
  kind = EXCLUDED.kind,
  track = EXCLUDED.track,
  min_elo = EXCLUDED.min_elo,
  max_elo = EXCLUDED.max_elo,
  xp_reward = EXCLUDED.xp_reward,
  elo_reward = EXCLUDED.elo_reward,
  fen = EXCLUDED.fen,
  solution_ucis = EXCLUDED.solution_ucis,
  fantasy_rules = EXCLUDED.fantasy_rules,
  prompt = EXCLUDED.prompt,
  hints = EXCLUDED.hints,
  insight = EXCLUDED.insight,
  sort_order = EXCLUDED.sort_order,
  is_published = EXCLUDED.is_published;

-- Ensure only one published puzzle per level per track
UPDATE campaign_puzzles SET is_published = false
WHERE track = 'main' AND sort_order BETWEEN 10 AND 20 AND is_published = true
  AND slug NOT IN (
    'std-010-rook-mate','std-011-knight-fork','std-012-queen-capture','std-013-bishop-pin',
    'std-014-mate-in-1','std-015-rook-check','std-016-knight-capture','std-017-queen-mate',
    'std-018-bishop-mate','std-019-rook-capture','std-020-queen-mate'
  );

UPDATE campaign_puzzles SET is_published = false
WHERE track = 'fantasy' AND sort_order BETWEEN 4 AND 20 AND is_published = true
  AND slug NOT LIKE 'fantasy-0%';
